# --- CONEXAO COM O SUPABASE ---
# Substitua [SUA_SENHA] pela senha que voce definiu no Supabase
spring.datasource.url=jdbc:postgresql://db.hmhpxavrootipfmkoztw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=midvex-Sezfi0-nebxiq
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACAO DO HIBERNATE (CRIACAO DE TABELAS) ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACAO DE UPLOAD DE PDF ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- AJUSTE DE DATA/HORA (PARA O RH DO HMLMB) ---
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# --- CONFIGURACAO JACKSON (JSON) ---
spring.jackson.serialization.write-dates-as-timestamps=false
